name: build-push-github-action

description:
  "publishes a docker image of the Dockerfile in the root of this repository to ghcr.io"

inputs:
  token:
    description: 'Authentication Token'
    required: true
  username:
    description: 'ghcr username'
    required: true
    default: ${{ github.actor }}

runs:
  using: "composite"
  steps:
    - name: Log in to the Container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/${{ github.repository }} # registry/image-name

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
