name: build-push-github-action

description:
  "publishes a docker image of the Dockerfile in the root of this repository to ghcr.io"

inputs:
  token:
    description: 'Authentication Token'
    required: true
  context:
    description: 'context - defaults to .'
    required: true
    default: .
  file:
    description: 'Dockerfile - defaults to Dockerfile in Root'
    required: true
    default: ./Dockerfile
  username:
    description: 'ghcr username - defaults to actor'
    required: true
    default: ${{ github.actor }}
  image_name:
    description: 'image_name - defaults to repo name'
    required: true
    default: ${{ github.repository }}
  tag:
    description: 'tag - defaults to branch'
    required: true
    default: ${{ github.ref_name }}
  platforms:
    description: 'target platforms (comma separated)'
    required: false
    default: linux/amd64

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      if: contains(inputs.platforms, 'arm') || contains(inputs.platforms, ',')
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v2.1.0
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.token }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ghcr.io/${{ inputs.image_name }} # registry/image-name
        tags: |
          type=raw,value=${{ inputs.tag }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: true
        platforms: ${{ inputs.platforms }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
